
# validation

- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
    - autologin_pass

# required dependencies

- name: make sure temp folder exists
  file:
    path: "{{ temp_folder }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  become: yes
 
# copy files to scipts folder

- name: copy autologin files to temp folder
  copy:
    src: "{{ item }}"
    dest: "{{ temp_folder }}"
    mode: '0777'
  with_items:
    ['enable_autologin','kcpassword']

# fix CR for osx

- name: change the carrige return to osx style
  shell: "tr '\n' '\r' < {{ item }} > {{ item }}1 && mv {{ item }}1 {{ item }} && chmod 777 *"
  args:
    chdir: "{{ temp_folder }}"
  with_items:
    ['enable_autologin','kcpassword']

# enable autologin

- name: enable autologin
  shell:  "/bin/sh enable_autologin '{{ ansible_user_id }}' '{{ autologin_pass }}'"
  args:
    chdir: "{{ temp_folder }}"
  async: 300
  poll: 5
  become: yes
