
# validation

- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
    - autologin_pass

# required dependencies

- name: make sure temp folder exists
  file:
    path: "{{ temp_folder }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  become: yes
 
# copy files to scipts folder

- name: copy autologin files to temp folder
  copy:
    src: "{{ item }}"
    dest: "{{ temp_folder }}"
    mode: '0777'
  with_items:
    ['enable_autologin','kcpassword']

# enable autologin

- name: enable autologin
  command:  "sudo /bin/sh enable_autologin {{ ansible_user_id }} {{ autologin_pass }}"
  args:
    chdir: "{{ temp_folder }}"
