---

- name: validate vars
  include_tasks: tasks/variables.yml

- name: validate auto login
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-autologin.yml"
  when: 
    - state|default('present') == 'present' 
    - enable_autologin == True
    - deploy | default('true') | bool

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: 
    - state|default('present') == 'present'
    - download | default('true') | bool

- name: deploy selenium
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-deploy.yml"
  when: 
    - state|default('present') == 'present'
    - deploy | default('true') | bool

- name: clear temp folder
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-clear-temp.yml"
  when: 
    - clear_temp_folder | default('no') | bool

- name: uninstall
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-uninstall.yml"
  when: state|default('present') == 'absent'
